### ISSUE TITLE
[question] How do I include the data that's from `load` function?

### ISSUE THREAD

**Issue by Sinderella** [muonw/powertable#14]
I am new to svelte, so I am probably misunderstanding things.

I noticed that I cannot include the data that's fetched from the server side (`+page.server.ts`). Normally, it'd be available in the `data: PageData` variable. It's somewhat "remote", but I am not sure how do I integrate that with the `dataFeed` function, or if it's the correct way to do what I want.

Cheers!

**Comment by muonw-public** [comment]
You can use [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) inside `dataFeed` to retrieve data from [an API endpoint on your server](https://kit.svelte.dev/docs/routing#server).

`+page.server.ts` wouldn't be useful in this case. Here is the gist of what you can do to get the first page load. But in order to make it fully functional, you will need to pass `filters`, `options`, and `search` objects to the API and do all the processing (e.g. sorting, filtering, etc.) on the server before returning a response (also see the source code of [this example](https://muonw.github.io/powertable/examples/example6)).

/my-sveltekit-project/src/routes/api/table/+server.js
```js
export function GET() {
    return new Response(JSON.stringify(
        {
            instructs: [],
            options: [],
            data: [{"id": 1, "name": "Fay"}, {"id": 2, "name": "Luca"}]
        }
    ));
}
```
/my-sveltekit-project/src/routes/+page.svelte

```svelte
<script>
import { PowerTable } from '@muonw/powertable';

let ptData = [];
let ptOptions = {
    isDataRemote: true,
    userFunctions: {
        dataFeed: apiCall,
    },
}

async function apiCall({filters, options, search}) {
    // adjust the API link if needed
    const response = await fetch('http://localhost:5173/api/table')
    .then((response) => response.json())
    .then((data) => data);
    return response;
}
</script>

<div class="MuonW PowerTable">
    <PowerTable {ptOptions} {ptData} />
</div>
```

**Comment by Sinderella** [comment]
Awesome! Thank you very much for your help.

I am sure I'll be able to figure things out from here, so I'll close it now.

Cheers!
